// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\domain\service\orders\interface.go

// Package mock_orders is a generated GoMock package.
package mock_orders

import (
	context "context"
	reflect "reflect"

	models "github.com/dmitastr/yp_gophermart/internal/domain/models"
	orders "github.com/dmitastr/yp_gophermart/internal/domain/service/orders"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(arg0 context.Context, arg1 string) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), arg0, arg1)
}

// GetOrders mocks base method.
func (m *MockService) GetOrders(arg0 context.Context, arg1 string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", arg0, arg1)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockServiceMockRecorder) GetOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockService)(nil).GetOrders), arg0, arg1)
}

// GetWithdrawals mocks base method.
func (m *MockService) GetWithdrawals(arg0 context.Context, arg1 string) ([]models.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", arg0, arg1)
	ret0, _ := ret[0].([]models.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockServiceMockRecorder) GetWithdrawals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockService)(nil).GetWithdrawals), arg0, arg1)
}

// PostOrder mocks base method.
func (m *MockService) PostOrder(arg0 context.Context, arg1 *models.Order) (*orders.WorkerResult, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostOrder", arg0, arg1)
	ret0, _ := ret[0].(*orders.WorkerResult)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// PostOrder indicates an expected call of PostOrder.
func (mr *MockServiceMockRecorder) PostOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOrder", reflect.TypeOf((*MockService)(nil).PostOrder), arg0, arg1)
}

// PostWithdraw mocks base method.
func (m *MockService) PostWithdraw(arg0 context.Context, arg1 *models.Withdraw) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostWithdraw", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostWithdraw indicates an expected call of PostWithdraw.
func (mr *MockServiceMockRecorder) PostWithdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostWithdraw", reflect.TypeOf((*MockService)(nil).PostWithdraw), arg0, arg1)
}
