name: Go Test and Coverage
on:
  push:
    branches:
      - main
      - development
      - readme
  pull_request:
    branches:
      - main
      - development
      - readme
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Or your desired Go version

      - name: Run tests and generate coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Get coverage percentage
        id: get_coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/\%//')
          echo "coverage_percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c2e11faf0eaeaf3059a1868038b74ee5
          filename: badge.json
          label: Coverage
          message: ${{ steps.get_coverage.outputs.coverage_percentage }}%
          color: green # Or dynamically set based on percentage
          style: flat-square
